"""votes

Revision ID: d97f47e5cee6
Revises: 0c1101b074dc
Create Date: 2019-04-22 23:53:41.226575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97f47e5cee6'
down_revision = '0c1101b074dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('upvote_id', sa.Integer(), nullable=True),
    sa.Column('downvote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['downvote_id'], ['recommendation.id'], ),
    sa.ForeignKeyConstraint(['upvote_id'], ['recommendation.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
